### ISSUE TITLE
Mobile compatibility issue

### ISSUE THREAD

**Issue by Hari-Bonda** [datitisev/flarum-discussion-agree-message#2]
Hi, I am experiencing an issue while trying to start a discussion from mobile. could you plz look into this.

the input text area is getting hidden.

![image](https://user-images.githubusercontent.com/5230394/131909071-5c37aea1-c3d3-4db2-9d87-3328dfa8c147.png)

thanks in advance :)

**Comment by dsevillamartin** [comment]
This is probably more of a core bug but i've "fixed" it here as well.

**Comment by Hari-Bonda** [comment]
Hi, after updating to the new version unable to start a discussion, it is not allowing me to write the post.

it is only allowing me to write post when i hit on I agree button. is it supposed to work in that way?

**Comment by dsevillamartin** [comment]
@Hari-Bonda Yes, that is intended. Same way prevent necrobumping ext does it.

**Comment by Hari-Bonda** [comment]
> @Hari-Bonda Yes, that is intended. Same way prevent necrobumping ext does it.

Could change it, post discussion button need to be dim and when user hits I agree "post discussion" button needs to get dark.

Allow the user to enter title and write post and select tags even when not agreed.

Highlight post discussion button when the user hits I agree button. (Desktop and mobile)

**Comment by dsevillamartin** [comment]
I personally don't think it's a big deal... do you need it changed that much? If so I'd just remove the disabling, as adding more stuff to the button usually doesn't end well in my experience.

**Comment by Hari-Bonda** [comment]
> I personally don't think it's a big deal... do you need it changed that much? If so I'd just remove the disabling, as adding more stuff to the button usually doesn't end well in my experience.


If the extension is enabled user will not get keyboard after hitting start discussion.

In my case my users are not that much technical to understand this behaviour.

You are right, just allow the user to input he will end up seeing keyboard. (No changes needed to start discussion button)

So if user hits start button he will see this.

![IMG_20210905_091656.jpg](https://user-images.githubusercontent.com/5230394/132114365-e8f4af40-d5ae-49ea-891f-f0de3fa363a0.jpg)



![Screenshot_20210905-090434.jpg](https://user-images.githubusercontent.com/5230394/132114084-436d3a5d-0e20-456f-b9c0-3a2a51528d90.jpg)

### Solved: this feature was added in v1.0.2

![image](https://user-images.githubusercontent.com/5230394/132131264-db203c17-dba8-47a5-852d-7278555b5697.png)
