### ISSUE TITLE
Update repository URL at Packagist

### ISSUE THREAD

**Issue by rob006** [datitisev/flarum-discussion-agree-message#4]
Could you update source URL on Packagist (using form at https://packagist.org/packages/datitisev/flarum-discussion-agree-message/edit)? My Weblate bot is having problems with this extension because all tags in [Packagist API](https://packagist.org/p2/datitisev/flarum-discussion-agree-message.json) points to an old URL (https://github.com/datitisev/flarum-discussion-agree-message) as a source, and some GitHub endpoints do not seem to handle redirections correctly. As a result bot does not detect any translations for this extension: https://github.com/rob006-software/flarum-translations/commit/51e311c67e56e4d34d7c029343136e368d830ae5.

AFAIK Packagist changes source for old tags only when you change repository URL using Packagist web interface.

**Comment by dsevillamartin** [comment]
:+1: Done. Thanks for the heads up.
